# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.12.1.dev1+g575de39.d20230918'
__version_tuple__ = version_tuple = (1, 12, 1, 'dev1', 'g575de39.d20230918')
